import Head from "next/head";
import Link from "next/link";
import React from "react";

const Main = ({ children, title }: { children: React.ReactElement, title:string }) => {
    return <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className='bg-green-300 flex overflow-hidden'>
            <div className='w-2/12 h-screen bg-[#0f203c] text-white'>
                <ul className='mt-10'>
                    {
                        [
                            {
                                label: 'All',
                                href: "/"
                            },
                            {
                                label: 'Add New',
                                href: "/add"
                            },
                        ].map((item, index) => <Link  key={index} href={item.href} ><li className='py-2 px-4 hover:bg-[#132a50] cursor-pointer '>{item.label}</li></Link>)
                    }
                </ul>
            </div>
            <div className='w-10/12 bg-gray-200 p-2 px-10 flex flex-col justify-center items-center overflow-auto'>
               <div className="flex w-full mb-3 justify-start ">
               <h1 className="text-4xl">{title}</h1>
               </div>
                <div className=' bg-white shadow p-5'>
                    {children}
                </div>
            </div>
        </div>
    </div>

}
export default Main;