import Head from "next/head";
import Link from "next/link";
import React from "react";

const Main = ({ children, title }: { children: React.ReactElement, title: string }) => {
    return <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className=' flex overflow-hidden'>
            <div className='w-2/12 h-screen bg-[#0f203c] text-white'>
                <ul className='mt-10'>
                    {
                        [
                            {
                                label: 'All',
                                href: "/"
                            },
                            {
                                label: 'Add New',
                                href: "/add"
                            },
                        ].map((item, index) => <Link key={index} href={item.href} ><li className='py-2 px-4 hover:bg-[#132a50] cursor-pointer '>{item.label}</li></Link>)
                    }
                </ul>
            </div>
            <div className='w-10/12 pt-20 bg-gray-200  flex flex-col overflow-auto '>
                <div className="container mx-auto max-w-6xl ">
                    <div className=' '>
                        {children}
                    </div>
                </div>
            </div>
        </div>
    </div>

}
export default Main;