import Head from "next/head";
import Link from "next/link";
import React from "react";
import { AiOutlinePlusCircle } from "react-icons/ai";
import { FiUsers } from "react-icons/fi";
import { MdClearAll } from "react-icons/md";

const Main = ({ children, }: { children: React.ReactElement, }) => {
    const links = [
        {
            label: 'All',
            href: "/",
            icon: <MdClearAll size={23} />
        },
        {
            label: 'Clients',
            href: "/clients",
            icon: <FiUsers size={23} />
        },
        {
            label: 'Add New',
            href: "/add",
            icon: <AiOutlinePlusCircle size={23} />
        },
        {
            label: 'Add Client',
            href: "/newclient",
            icon: <AiOutlinePlusCircle size={23} />
        },
    ]
    return <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className=' flex w-screen h-screen overflow-hidden '>
            <div className='w-2/12 h-screen overflow-hidden bg-[#031e49] text-white'>
                <ul className='mt-10 '>
                    {
                        links.map((item, index) => <Link key={index} href={item.href} >
                            <li className='py-4 px-4 hover:bg-[#455e87] cursor-pointer '>
                                <div className="flex items-center ml-3">
                                    {
                                        item.icon
                                    }
                                    <h1 className="ml-4">
                                        {item.label}
                                    </h1>
                                </div>
                            </li>
                        </Link>)
                    }
                </ul>
            </div>
            <div className='w-10/12 pt-20 bg-gray-200  flex flex-col overflow-auto '>
                <div className="container mx-auto max-w-6xl ">
                    <div className=' mb-10'>
                        {children}
                    </div>
                </div>
            </div>
        </div>
    </>

}
export default Main;